### ISSUE TITLE
google support for profiles.ihe.net

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#34]
Is there something we need to do to have google crawl and make searches available on profiles.ihe.net? We have had a prototype of our ITI Technical Framework up there for weeks and still no google search results. (It is possible that the switch to https might have been required by google) @ccarr

**Comment by vassilpeytchev** [comment]
I was just looking at this. Many people may prefer DuckDuckGo, and it turns out they (DDG) simply reuse non-Google search engines. This means that if we register register https://profiles.ihe.net with Bing, DuckDuckGo will return search results.
Bing registration is at https://www.bing.com/toolbox/webmaster - let me know when this is done, and I will add a search box to every page, that can hit DDG.

**Comment by vassilpeytchev** [comment]
There is now search in the header, that queries Google. The above "Bing registration" is still something useful - when it is done, I can switch it easily to DuckDuckGo.
