### ISSUE TITLE
Infrastructure needs documented for Gazelle to support ATNA message use

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#62]
Lynn and John to writing up the requirements for improvements to Gazelle to support ITI using Gazelle as the method for documenting ATNA audit message profiling and use in profiles.ihe.net as the method of communicating the requirements to the public.

**Comment by JohnMoehrke** [comment]
Notes from Connectathon:
1) Gazelle is missing audit message specifications for many of ITI fhir based profiles
2) Gazelle validators should validate the audit message when it comes in on the FHIR AuditEvent feed (can translate and validate, or create FHIR structureDefinition validation).
3) Gazelle could/should be able to import a FHIR structureDefinition profile of audit events and create the audit message page from that. (for example, MHD implementation guide now has these).

**Comment by lynnfel** [comment]
Here is a working document with details about this: https://docs.google.com/document/d/1cDe9XxukQd2bD1hPD2VRRUcRGZtjH5tAOqmhBK-1Uns/edit#

**Comment by JohnMoehrke** [comment]
Issue covering what was changed in the TF as an experiment https://github.com/IHE/publications/issues/15

**Comment by lynnfel** [comment]
Taking a look at this, and moving towards documenting rqmts for the GSS developers....

In https://profiles.ihe.net/ITI/TF/Volume2/ITI-18.html#3.18.5.1.1, you have pointed to the GSS audit definition followed by a 'where' statement with a bullet list of value constraints.  OK...

In https://gazelle.ihe.net/gss/audit-messages/view.seam?id=16, we know that the easily test able value constraints (eg EV('110153', 'DCM', 'Source Role ID')  are included in the tables, and tested by GSS.  And, the more narrative constraints (eg "If Asynchronous Web Services Exchange is being used, the content of the <wsa:ReplyTo/> element. Otherwise, not specialized.") are documented in GSS in an "Extra Constraints" section at the bottom, under the tables.    When a validation is performed, these extra constraints appear as 'warnings' in the results, ie not tested by the tool.

QUESTION:  Rather than adding the value constraints as a bullet list in the TF Vol 2, why not just include them completely in the "Extra Constraints" section of the Audit definition in GSS?

IDEALLY, in GSS, I think we want the constraints to appear in the tables (as they did in the TF) for user-friendliness.   When creating an audit record definition, there would need to be a way to mark a specific constraint as testable.

**Comment by lynnfel** [comment]
John -- I have done some work to add detail to a document that describes the current state of audit record documentation and validation, and enhancements to the tools.  I will continue to add content in the coming days, but there's enough there to share https://docs.google.com/document/d/1cDe9XxukQd2bD1hPD2VRRUcRGZtjH5tAOqmhBK-1Uns/edit#

I'm happy to move the content out of google docs and into Github in some format you would suggest....
