### ISSUE TITLE
support Search 

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#8]
from the IHE-USA survey of the IHE audience there was strong comments around search. Some were upset we were leaving PDF as PDF is searchable, they were worried they wouldn't be able to do volume based searches (find XYZ anywhere in Volume2). Some were expecting that HTML would be better searchable (I presume they were expecting to use google, which should be available).

We should have a search in IHE that would limit the search results to the set of IHE specifications, the set of IHE domain X specifications, and the volume within a domain. I expect this is simply using google tooling. Need someone to figure this out,

**Comment by msmock** [comment]
Dear all

Not totally unexpected, since most experienced ITI FW user use the search to quickly find the relevant sections. They typically remember a keyword and the volume and do a PDF search. 

I have little experience with Google advanced search, so I’m of little help for this. But, if everything else fails or is not user friendly, we could setup a special index for the ITI TF using apache Solr and add a JavaScript search function to the page headers. This would require to run a Java Application Server in a public cloud. 

Regards
Martin

**Comment by vassilpeytchev** [comment]
I have added search, which does a default Google search within the whole of profiles.ihe.net.
