### ISSUE TITLE
Changes for CP-ITI-1247 "ATNA:  Retire STX: TLS 1.0 options"

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#84]
ITI has not yet moved its traditional CP process to Github issues; however, we will do a trial with CP-ITI-1247 which updates ATNA in Vol 1 (Ch 9) and in Vol 2 (ITI-19).     For now, this Github issue and CP-ITI-1247 represent the same changes.

The changes for this Github issue are contained in the following  pull request for updates to ATNA published in html on profiles.ihe.net:

https://github.com/IHE/publications/pull/83

**Comment by JohnMoehrke** [comment]
Tracking information:

  ------------------------- -------------------
  IHE Domain                IT Infrastructure
  Change Proposal ID:       CP-ITI-1247
  Change Proposal Status:   Completed
  Date of last update:      Apr 8, 2021
  Person assigned:          Lynn Felhofer
  ------------------------- -------------------

Change Proposal Summary information:

+----------------------------------+----------------------------------+
| ATNA: Retire STX: TLS 1.0        |                                  |
| options                          |                                  |
+----------------------------------+----------------------------------+
| Submitter's Name(s) and e-mail   | John Moehrke                     |
| address(es):                     |                                  |
+----------------------------------+----------------------------------+
| Submission Date:                 | Apr 2, 2021                      |
+----------------------------------+----------------------------------+
| Integration Profile(s) affected: | ATNA                             |
+----------------------------------+----------------------------------+
| Actor(s) affected:               | Secure Node & Secure App         |
+----------------------------------+----------------------------------+
| IHE Technical Framework or       | IHE TF Vol 1 and 2 Rev 19.0      |
| Supplement modified:             | Final Text Dec 2, 2020           |
+----------------------------------+----------------------------------+
| Volume(s) and Section(s)         | Vol 1                            |
| affected:                        |                                  |
+----------------------------------+----------------------------------+
| **Rationale for Change:**        |                                  |
|                                  |                                  |
| Given the way we wrote some of   |                                  |
| the ATNA options, they have      |                                  |
| magically updated because the    |                                  |
| IETF has updated BCP195 last     |                                  |
| month: <https                    |                                  |
| ://tools.ietf.org/html/rfc8996>  |                                  |
|                                  |                                  |
| Specifically, the  ATNA options  |                                  |
| \"STX: TLS 1.0 Floor using       |                                  |
| BCP195\" and "STX: TLS 1.0 with  |                                  |
| AES" are now invalid. One cannot |                                  |
| use TLS 1.0 and be compliant     |                                  |
| with BCP195. Prior to the IETF   |                                  |
| update to BCP195 there was an    |                                  |
| allowed downgrade under very     |                                  |
| specific conditions. This        |                                  |
| pathway is no longer allowed in  |                                  |
| BCP195.                          |                                  |
|                                  |                                  |
| The other option that called     |                                  |
| upon BCP195 is okay as it        |                                  |
| specified TLS 1.2.               |                                  |
|                                  |                                  |
| Editor's note: This Github issue |                                  |
| is equivalent to this CP:        |                                  |
| <https://github.                 |                                  |
| com/IHE/publications/issues/84>. |                                  |
| Eventually we expect track       |                                  |
| changes to the ITI TF HTML       |                                  |
| publication using Github issues  |                                  |
| alone, but that process is still |                                  |
| to-be-finalized.                 |                                  |
+----------------------------------+----------------------------------+
